force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Represents a candidate&apos;s application to a position.</description>
    <label>Job Application</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Position_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Web_Position_External_ID__c</fullName>
    <label>(Web)Position External ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Active_position__c.field-meta.xml
<CustomField>
    <fullName>Active_position__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active position?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Position_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Position External ID</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AssignPositionHandler.cls
public class AssignPositionHandler {
    
    public static void setsPosition(List<Position__c> positions){
        
        List<String> posId = new List<String>();
        for(Position__c pos : positions){
            posId.add(pos.Position_External_ID__c);
        }
        
        List<Job_Application__c> applications = [SELECT Job_Position__c, Web_Position_External_ID__c FROM Job_Application__c WHERE Web_Position_External_ID__c IN:posId];
        for(Position__c newPOs : positions){
            for(Job_Application__c app : applications){
                if(app.Job_Position__c == null){
                    app.Job_Position__c = newPos.Id;
                }
            } 
        }
        update applications;
    }
    
    
    public static void assignActivePosition(List<Position__c> positions){
        List<String> posId = new List<String>();
        for(Position__c pos : positions){
            posId.add(pos.Position_External_ID__c);
        }
        
        List<Job_Application__c> applications = [SELECT Web_Position_External_ID__c FROM Job_Application__c WHERE Web_Position_External_ID__c IN:posId];
        for(Position__c pos : positions){
            for(Job_Application__c app : applications){
                if(pos.Position_External_ID__c == app.Web_Position_External_ID__c && pos.Active_position__c == true){
                    app.Job_Position__c = pos.Id;
                }
            } 
        }
        update applications;

    }
}