force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Represents a candidate&apos;s application to a position.</description>
    <label>Job Application</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Web_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Applicant_Name__c</fullName>
    <label>(Web)Applicant&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Web_Attachment__c</fullName>
    <label>(Web)Attachment</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Email__c.field-meta.xml
<CustomField>
    <fullName>Web_Email__c</fullName>
    <label>(Web)Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Web_Lead_Source__c</fullName>
    <label>(Web)Lead Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Web_Phone_Number__c</fullName>
    <label>(Web)Phone Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Position__c.field-meta.xml
<CustomField>
    <fullName>Web_Position__c</fullName>
    <label>(Web)Position</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Position_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Web_Position_External_ID__c</fullName>
    <label>(Web)Position External ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/APICall.cls
@RestResource(urlMapping='/api/JobApp/*')
Global with sharing class APICall {
    
    @HttpPost
    global static String doPost(String leadSource, String name, String position, String email, String phone, String pId, String attachment, Id recordType){
        
        //Instance of the metadata type
        
        Job_Application__c jobApp = new Job_Application__c();
        jobApp.Web_Applicant_Name__c = name;
        jobApp.Web_Lead_Source__c = leadSource;
        jobApp.Web_Email__c = email;
        jobApp.Web_Phone_Number__c = phone;
        jobApp.Web_Position__c = position;
        jobApp.Web_Position_External_ID__c = pId;
        jobApp.Web_Attachment__c = attachment;
        jobApp.RecordTypeId = recordType;
        
        insert jobApp;
        return 'Submitted successfully';
    }

}