force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Represents a candidate&apos;s application to a position.</description>
    <label>Job Application</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Phone_number__c.field-meta.xml
<CustomField>
    <fullName>Phone_number__c</fullName>
    <label>Phone number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Applicant_Name__c</fullName>
    <label>(Web)Applicant&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Web_Attachment__c</fullName>
    <label>(Web)Attachment</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Email__c.field-meta.xml
<CustomField>
    <fullName>Web_Email__c</fullName>
    <label>(Web)Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Web_Lead_Source__c</fullName>
    <label>(Web)Lead Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Web_Phone_Number__c</fullName>
    <label>(Web)Phone Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Active_position__c.field-meta.xml
<CustomField>
    <fullName>Active_position__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active position?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Position_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Position External ID</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Life_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Position_Life_Cycle__c</fullName>
    <label>Position&apos;s Life Cycle</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trainee</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTestClass.cls
@isTest
public class JobApplicationTestClass {
    
    @isTest
    public static void jobApplicationTest(){
        
        Position__c pos = new Position__c();
        pos.Name = 'example';
        pos.Active_position__c = true;
        pos.Name = 'ExamplePos';
        pos.Position_External_ID__c ='0011';
        pos.Position_Life_Cycle__c ='Other';
        pos.Min_Pay__c = 1000;
        pos.Max_Pay__c = 1500; 
        
        insert pos;
        
        Job_Application__c app = new Job_Application__c();
        app.Name = 'Test Application1';
        app.Email_Address__c = 'Emailtesting@gmail.com';
        app.Phone_number__c = '1234-5678';
        app.Job_Position__c = pos.Id;
        
        insert app;
        
        Job_Application__c jobA = new Job_Application__c(
            Web_Applicant_Name__c = 'webName',
            Web_Email__c ='webWmail@gmail.com',
            Web_Phone_Number__c = 'webphone',
            Web_Lead_Source__c = 'webleadsource',
            Web_Attachment__c = 'noAttachment'
        );
        
        insert jobA;
        
    }
}