force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Represents a candidate&apos;s application to a position.</description>
    <label>Job Application</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Web_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Applicant_Name__c</fullName>
    <label>(Web)Applicant&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Web_Attachment__c</fullName>
    <label>(Web)Attachment</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Email__c.field-meta.xml
<CustomField>
    <fullName>Web_Email__c</fullName>
    <label>(Web)Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Web_Lead_Source__c</fullName>
    <label>(Web)Lead Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Web_Phone_Number__c</fullName>
    <label>(Web)Phone Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Position__c.field-meta.xml
<CustomField>
    <fullName>Web_Position__c</fullName>
    <label>(Web)Position</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Position_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Web_Position_External_ID__c</fullName>
    <label>(Web)Position External ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/recordTypes/Not_Referred.recordType-meta.xml
<RecordType>
    <fullName>Not_Referred</fullName>
    <active>true</active>
    <label>Not Referred</label>
</RecordType>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Active_position__c.field-meta.xml
<CustomField>
    <fullName>Active_position__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active position?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Position_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Position External ID</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Life_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Position_Life_Cycle__c</fullName>
    <label>Position&apos;s Life Cycle</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trainee</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/recordTypes/Operations_Position.recordType-meta.xml
<RecordType>
    <fullName>Operations_Position</fullName>
    <active>true</active>
    <description>For all Operation positions</description>
    <label>Operations Position</label>
</RecordType>

force-app/main/default/classes/AssignPositionTestClass.cls
@isTest
public class AssignPositionTestClass {
    
    @isTest
    public static void AssignPositionTest(){
       
        test.startTest();
        String recordType = Schema.SObjectType.Job_Application__c.getRecordTypeInfosByDeveloperName().get('Not_Referred').getRecordTypeId();
        Job_Application__c ja = new Job_Application__c();
        ja.Name = 'testName';
        ja.Web_Applicant_Name__c = 'testName';
        ja.Web_Email__c = 'newApplication@gmail.com';
        ja.Web_Phone_Number__c = '1234-5678';
        ja.Web_Attachment__c = 'no attachment';
        ja.Web_Position__c = 'newItPosition';
        ja.Web_Position_External_ID__c = '1111';
        ja.Web_Lead_Source__c = 'Facebook';  
        ja.RecordTypeId = recordType;
        insert ja;
        
        String posRecordType = Schema.SObjectType.Position__c.getRecordTypeInfosByDeveloperName().get('Operations_Position').getRecordTypeId();
        Position__c p = new Position__c();
        p.RecordTypeId = posRecordType;
        p.Name = 'newItPosition';
        p.Active_position__c = true;
        p.Position_External_ID__c ='1111';
        p.Position_Life_Cycle__c ='Trainee';
        p.Min_Pay__c = 1000;
        p.Max_Pay__c = 1500;  
        insert p;
        
		//creating inactive position
        Position__c inPos = new Position__c();
        inPos.RecordTypeId = posRecordType;
        inPos.Name = 'InactivePosition';
        inPos.Active_position__c = false;
        inPos.Position_External_ID__c ='1122';
        inPos.Position_Life_Cycle__c ='Trainee';
        inPos.Min_Pay__c = 1000;
        inPos.Max_Pay__c = 1500;    
        insert inPos;
        
        //Job application with inactive position
        Job_Application__c jaInactive = new Job_Application__c();
        jaInactive.Name = 'testName2';
        jaInactive.Web_Applicant_Name__c = 'testName';
        jaInactive.Web_Email__c = 'newApplication2@gmail.com';
        jaInactive.Web_Phone_Number__c = '1234-5678';
        jaInactive.Web_Attachment__c = 'no attachment';
        jaInactive.Web_Position__c = 'InactivePosition';
        jaInactive.Web_Position_External_ID__c = '1122';
        jaInactive.Web_Lead_Source__c = 'Facebook';  
        jaInactive.RecordTypeId = recordType;
        insert jaInactive;

        //updating job Application with active position
        inPos.Active_position__c = true;
        upsert inPos;
        test.stopTest();

    }

}