force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Candidate__c/recordTypes/Trainee.recordType-meta.xml
<RecordType>
    <fullName>Trainee</fullName>
    <active>true</active>
    <label>Trainee</label>
</RecordType>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Represents a candidate&apos;s application to a position.</description>
    <label>Job Application</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Computrabajo</fullName>
            </value>
            <value>
                <fullName>Un Mejor Empleo</fullName>
            </value>
            <value>
                <fullName>BuscoJobs</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Universidad Don Bosco</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Phone_number__c.field-meta.xml
<CustomField>
    <fullName>Phone_number__c</fullName>
    <label>Phone number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Applicant_Name__c</fullName>
    <label>(Web)Applicant&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Web_Attachment__c</fullName>
    <label>(Web)Attachment</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Email__c.field-meta.xml
<CustomField>
    <fullName>Web_Email__c</fullName>
    <label>(Web)Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Web_Lead_Source__c</fullName>
    <label>(Web)Lead Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Web_Phone_Number__c</fullName>
    <label>(Web)Phone Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Position__c.field-meta.xml
<CustomField>
    <fullName>Web_Position__c</fullName>
    <label>(Web)Position</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Web_Position_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Web_Position_External_ID__c</fullName>
    <label>(Web)Position External ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Active_position__c.field-meta.xml
<CustomField>
    <fullName>Active_position__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active position?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Position_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Position External ID</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Life_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Position_Life_Cycle__c</fullName>
    <label>Position&apos;s Life Cycle</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trainee</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationHandler.cls
public class JobApplicationHandler {
    
    
    //Method to create new job applications and candidates at the same time
    public static void createNewCandidate(List<Job_Application__c> jobApps){
        
        List<String> aplIds = new List<String>();
        for(Job_Application__c newjb : jobApps){
            aplIds.add(newjb.Web_Email__c);
            aplIds.add(newjb.Email_Address__c);
        }
        
        List<String> plusPosList = new List<String>();
        for(Job_Application__c newPs : jobApps){
            plusPosList.add(newPs.Job_Position__c);
        }
        
        List<String> webPlusPosList = new List<String>();
        for(Job_Application__c newPs : jobApps){
            webPlusPosList.add(newPs.Web_Position_External_ID__c);
        }
        
        List<Candidate__c> candidates = [SELECT Email_Address__c FROM Candidate__c WHERE Email_Address__c IN :aplIds];
        List<Candidate__c> newCan = new List<Candidate__c>();   
        List<Position__c> plusPosi = [SELECT Position_Life_Cycle__c FROM Position__c WHERE Id = :plusPosList];
        List<Position__c> webPlusPosi = [SELECT Position_Life_Cycle__c FROM Position__c WHERE Position_External_ID__c = :webPlusPosList];
        
        Id recordType;
        for(Job_Application__c apps : jobApps){
            if(apps.Job_Position__c == null || apps.Web_Position__c == null){
                recordType = Schema.SObjectType.Candidate__c.getRecordTypeInfosByDeveloperName().get('Trainee').getRecordTypeId();
            }
        }
            
        for(Position__c ps : plusPosi){
            if(ps.Position_Life_Cycle__c == 'Trainee'){
                recordType = Schema.SObjectType.Candidate__c.getRecordTypeInfosByDeveloperName().get('Trainee').getRecordTypeId();
            }else{
                recordType = Schema.SObjectType.Candidate__c.getRecordTypeInfosByDeveloperName().get('Other').getRecordTypeId();
            }
        }
        
        for(Position__c ps2 : webPlusPosi){
            if(ps2.Position_Life_Cycle__c == 'Trainee'){
                recordType = Schema.SObjectType.Candidate__c.getRecordTypeInfosByDeveloperName().get('Trainee').getRecordTypeId();
            }else{
                recordType = Schema.SObjectType.Candidate__c.getRecordTypeInfosByDeveloperName().get('Other').getRecordTypeId();
            }
        }   
        
        
        for(Job_Application__c jobA : jobApps){             
            if(jobA.Email_Address__c != null){
                if(candidates.size() > 0){
                    break;
                }else{
                    //Creates new Candidate from CRM APP
                    newCan.add(new Candidate__c(
                        RecordTypeId = recordType,
                        Name = jobA.Name,
                        Email_Address__c = jobA.Email_Address__c,
                        Phone_number__c = jobA.Phone_number__c));  
                }
            }else{
                //Creates new Application from website
                if(candidates.size() > 0){
                    jobA.Name = jobA.Web_Applicant_Name__c;
                    jobA.Email_Address__c = jobA.Web_Email__c;
                    jobA.Phone_number__c = jobA.Web_Phone_Number__c;
                    jobA.Lead_Source__c = jobA.Web_Lead_Source__c;
                    jobA.Attachment__c = jobA.Web_Attachment__c;
                    jobA.Job_Position__c = getPositionId(jobApps);
                }else{
                    //Creates new Application and new Candidate from website
                    jobA.Job_Position__c = getPositionId(jobApps);
                    jobA.Name = jobA.Web_Applicant_Name__c;
                    jobA.Email_Address__c = jobA.Web_Email__c;
                    jobA.Phone_number__c = jobA.Web_Phone_Number__c;
                    jobA.Lead_Source__c = jobA.Web_Lead_Source__c;
                    jobA.Attachment__c = jobA.Web_Attachment__c;
                    newCan.add(new Candidate__c(
                        RecordTypeId = recordType,
                        Name = jobA.Web_Applicant_Name__c,
                        Email_Address__c = jobA.Web_Email__c,
                        Phone_number__c = jobA.Web_Phone_Number__c));
                }
            }
        }
        
        if(newCan.size() > 0){
            insert newCan;
            for(Job_Application__c jobB : jobApps){
                for(Candidate__c cc : newCan){
                    jobB.candidate__c = cc.Id;
                }
            }
        }
    }
    
    
    //Method to update the candidate's details
    public static void updateCandidate(List<Job_Application__c> jobApps){
        List<String> aplIds = new List<String>();
        for(Job_Application__c newjb : jobApps){
            aplIds.add(newjb.Email_Address__c);
            aplIds.add(newjb.Web_Email__c);
        }
        list<Candidate__c> candidates = [SELECT Email_Address__c, Name, Phone_number__c FROM Candidate__c WHERE Email_Address__c IN :aplIds];
        List<Candidate__c> can2 = new List<Candidate__c>();
        
        for(Job_Application__c jobA : jobApps){
            for(Candidate__c can : candidates){
                if(jobA.Email_Address__c == can.Email_Address__c){
                    can.Name = jobA.Name;
                    can.Phone_number__c = jobA.Phone_number__c;
                    can2.add(can);
                    
                }else if(jobA.Web_Email__c == can.Email_Address__c){
                    can.Name = jobA.Web_Applicant_Name__c;
                    can.Phone_number__c = jobA.Web_Phone_Number__c;
                    can2.add(can);
                }  
            }
        }
        update can2;
        for(Job_Application__c jobB : jobApps){
            for(Candidate__c cc : can2){
                jobB.candidate__c = cc.Id;
            }
        }
    }
    
    
    //Method to select the position id
    private static String getPositionId(List<Job_Application__c> jobApps){
        List<String> psIds = new List<String>();
        for(Job_Application__c newPos : jobApps){
            psIds.add(newPos.Web_Position_External_ID__c);    
        }
        
        String positionId;
        String message;
        List<Position__c> ps = [SELECT Position_External_ID__c, Name, Active_position__c FROM Position__c WHERE Position_External_ID__c IN: psIds];    
        
        for(Job_Application__c jbs : jobApps){
            for(Position__c positions : ps){               
                if(jbs.Web_Position_External_ID__c == positions.Position_External_ID__c && jbs.Web_Position__c == positions.Name && positions.Active_position__c == true){
                    positionId = positions.Id;
                }else if(jbs.Web_Position_External_ID__c == positions.Position_External_ID__c && positions.Active_position__c == false){
                    positionId = null;  
                }else{
                    positionId = null;
                }
            }
        }
        return positionId; 
        
    }
}